# Generated by Django 5.2.3 on 2025-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(default='Nairobi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Lipa na M-Pesa'), ('cod', 'Cash on Delivery')], default='mpesa', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0712345678', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_station',
            field=models.CharField(default='CBD', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
