# Generated by Django 5.2.3 on 2025-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
