# Generated by Django 5.2.3 on 2025-07-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_mpesa_phone_order_mpesa_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mpesa_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mpesa_receipt_number',
        ),
    ]
